### ISSUE TITLE
ROM - Switch software

### ISSUE THREAD

**Issue by oss003** [oss003/HTeMuLator#11]
Add BRAN - Automatic rom switch software

**Comment by sPhilM** [comment]
Is there a current memory map for this?

**Comment by oss003** [comment]
BRAN catches ERROR 94 to proces the given command. With a floating rom patch, it catches ERROR 94 and switches the rom at #a000 to check if the command can be executed in this rom. If all roms are tested and it's and unknown command, ERROR 94 is generated.
BRAN code is #499 bytes long, was originally written for #1000 but is included into the AtoMMC rom.
